var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/crews/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zzbyz0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0cakkt-.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mmnj9t._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0fhx__n._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_crews_page_actions_07-qw1m.js")
R.m(30625)
module.exports=R.m(30625).exports
